name: pandu_navigation
description: Offline Navigation & Survival System for Indonesian Hikers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State Management & Routing
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Map Engine (MapLibre - Corporate Grade)
  maplibre_gl: ^0.25.0

  # Local Persistence
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.8.3

  # Sensors & Location
  geolocator: ^11.0.0
  sensors_plus: ^4.0.2
  flutter_local_notifications: ^17.0.0

  # Utilities
  geodesy: ^0.10.0
  permission_handler: ^11.3.0
  archive: ^3.4.9
  # UI
  cupertino_icons: ^1.0.6
  dio: ^5.9.0
  fl_chart: ^1.1.1
  mbtiles: ^0.4.2
  audioplayers: ^6.5.1
  sunrise_sunset_calc: ^3.0.0
  vibration: ^3.1.5
  flutter_compass: ^0.8.0
  gpx: ^2.3.0
  google_fonts: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  drift_dev: ^2.15.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1



flutter:
  uses-material-design: true
  assets:
    - assets/map_styles/
    - assets/map_data/
    - assets/gpx/merbabu/
    - assets/fonts/
    - assets/config/
    - assets/icons/poi/


  fonts:
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
          weight: 300
